# Generated by Django 3.2.2 on 2021-05-21 08:38

from django.db import migrations
from random_word import RandomWords


def fill_tag(apps, schema_editor):
    tag = apps.get_model("app", "Tag")
    for i in range(1, 10100):
        word = RandomWords().get_random_word()
        while word is None:
            word = RandomWords().get_random_word()
        one_tag = tag(text=word)
        one_tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_answer_body'),
    ]

    operations = [
        migrations.RunPython(fill_tag),
    ]
