# Generated by Django 3.2.2 on 2021-05-21 08:48
from random import randint

from django.contrib.auth.models import User
from django.db import migrations
from faker import Faker
from app.models import *


def fill_tag(apps, schema_editor):
    tag = apps.get_model("app", "Tag")
    for i in range(1, 1):
        print(i)
        one_tag = tag(text=Faker().word())
        one_tag.save()


def fill_user(apps, schema_editor):
    user = apps.get_model("app", "User")
    for i in range(1, 1):
        print(i)
        one_user = user(username=Faker().simple_profile()['username'],
                        email=Faker().email(),
                        password=Faker().name())
        one_user.save()


def fill_question(apps, schema_editor):
    question = apps.get_model("app", "Question")
    for i in range(1, 1):
        print(i)
        one_question = question(
            author=User.objects.get(pk=randint(User.objects.first().id, User.objects.last().id)),
            title=Faker().paragraph(nb_sentences=1),
            text=Faker().text,
            date=Faker().date,
            tag=Tag.objects.get(pk=randint(Tag.objects.first().id, Tag.objects.last().id)),
            rating=randint(-100, 100),
        )
        one_question.save()


def fill_answer(apps, schema_editor):
    answer = apps.get_model("app", "Answer")
    for i in range(1, 1):
        print(i)
        one_answer = answer(body=Faker().text,
                            author=User.objects.get(pk=randint(User.objects.first().id, User.objects.last().id)),
                            date=Faker().date,
                            question=Question.objects.get(
                                pk=randint(Question.objects.first().id, Question.objects.last().id)),
                            rating=randint(-100, 100),
                            )
        one_answer.save()


def fill_like(apps, schema_editor):
    like = apps.get_model("app", "Like")
    for i in range(1, 1):
        print(i)
        obj = Answer.objects.get(pk=randint(Answer.objects.first().id, Answer.objects.last().id))
        one_like = like(user=User.objects.get(pk=randint(User.objects.first().id, User.objects.last().id)),
                        contentType=ContentType.objects.get_for_model(obj),
                        vote=1,
                        object_id=obj.id,
                        )
        one_like.save()

    for i in range(1, 1):
        print(i)
        obj = Question.objects.get(pk=randint(Question.objects.first().id, Question.objects.last().id))
        one_like = like(user=User.objects.get(pk=randint(User.objects.first().id, User.objects.last().id)),
                        contentType=ContentType.objects.get_for_model(obj),
                        vote=1,
                        object_id=obj.id,
                        )
        one_like.save()


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0006_auto_20210521_0838'),
    ]

    operations = [
        migrations.RunPython(fill_tag),
        migrations.RunPython(fill_like),
        migrations.RunPython(fill_answer),
        migrations.RunPython(fill_user),
        migrations.RunPython(fill_question),
    ]
