# Generated by Django 3.2.2 on 2021-05-21 08:48
from random import randint

from django.db import migrations
from faker import Faker
from app.models import *


def fill_tag(apps, schema_editor):
    tag = apps.get_model("app", "Tag")
    for i in range(1, 1):
        print(i)
        # one_tag = tag(text=Faker().word())
        # one_tag.save()


def fill_user(apps, schema_editor):
    print('User start')
    users = [User(username=Faker().simple_profile()['username'] + Faker().pystr()[:10],
                  email=Faker().email(),
                  password=Faker().name()) for i in range(1, 10001)]
    User.objects.bulk_create(users)
    print('User finish')


def fill_question(apps, schema_editor):
    print('question start')
    questions = [Question(
        author=User.objects.get(pk=randint(User.objects.first().id, User.objects.last().id)),
        title=Faker().paragraph(nb_sentences=1),
        text=Faker().text,
        date=Faker().date,
        rating=randint(-100, 100),
    ) for i in range(1, 100001)
    ]
    Tag.objects.set(pk=randint(Tag.objects.first().id, Tag.objects.last().id))
    Question.objects.bulk_create(questions)
    print('question finish')


def fill_answer(apps, schema_editor):
    print('answer start')
    answers = [Answer(body=Faker().text,
                      author=User.objects.get(pk=randint(User.objects.first().id, User.objects.last().id)),
                      date=Faker().date,
                      question=Question.objects.get(
                          pk=randint(Question.objects.first().id, Question.objects.last().id)),
                      rating=randint(-100, 100),
                      ) for i in range(1, 1000001)
               ]
    Answer.objects.bulk_create(answers)
    print('answer finish')


def fill_like(apps, schema_editor):
    print('like start')
    likes_answer = [Like(user=User.objects.get(pk=randint(User.objects.first().id, User.objects.last().id)),
                         content_type=ContentType.objects.get_for_model(Answer),
                         rating=1,
                         object_id=randint(Answer.objects.first().id, Answer.objects.last().id),
                         ) for i in range(1, 1000001)]
    Like.objects.bulk_create(likes_answer)
    likes_question = [Like(user=User.objects.get(pk=randint(User.objects.first().id, User.objects.last().id)),
                           content_type=ContentType.objects.get_for_model(Question),
                           rating=1,
                           object_id=randint(Question.objects.first().id, Question.objects.last().id),
                           ) for i in range(1, 1000001)]
    Like.objects.bulk_create(likes_question)
    print('like finish')


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0009_auto_20210521_1016'),
    ]

    operations = [
        # migrations.RunPython(fill_tag),
        # migrations.RunPython(fill_user),
        # migrations.RunPython(fill_question),
        # migrations.RunPython(fill_answer),
        # migrations.RunPython(fill_like),
    ]
